### PR TITLE
feat: make CSI dependencies up-to-date and do some tweaks.

### PR DESCRIPTION
**Pull request by Colstuwjx**
This PR is related to #11 , and focus on make the plugins in this repo up-to-date with upstream CSI standards, including:

* in k/k main repo, some utils has been moved or refactored, like `k8s.io/kubernetes/pkg/util/mount`, `mount.NewOsExec`;

* turn to use go module and update vendor dependencies, it could make us sync to the upstream more efficiently;

Thanks.

### CODE REVIEW

**Comment by Colstuwjx** [comment]
Hi @malc0lm ,

I have been tried my best to split my changes, and this is the first PR for my fork-to-upstream feedback. At the following PR, I'd like to make the plugins running into kube-system namespace, and enable leader election.

BTW, it's ONLY tested under CBS, and the others is not tested yet.

I also found that it's NOT same style between each plugins, for example, CBS and COSFS, it seems not synced to one version. I suggest we could learn something from azure csi repos, like [this one](https://github.com/kubernetes-sigs/azuredisk-csi-driver), split these plugins to some separate repos, or assign members to each plugin,  and I think our users could benifit to this if we could make each plugin up-to-date with the CSI upstream.

Thanks.

**Comment by malc0lm** [comment]
Thanks for your pr, could you split your pr to every single feature and commit, thanks.

**Comment by Colstuwjx** [comment]
OK, @malc0lm I have been reverted back the non-relevant changes, and this PR just focus on dependencies update.

**Comment by Colstuwjx** [comment]
I have been checked the build on my laptop, `Dockerfile.cfs`, `Dockerfile.cosfs`, `Dockerfile.launcher`, `Dockerfile.multistage.cbs`, all of these Dockerfile works well with cli: `docker build --network host -t yourimagename -f Dockerfile.xxx .`.

I think it's ready to merge, and the following PRs would be focusing on:

- [ ] update deploy yamls to sync with the code changes, as well as the build process;
- [ ]  split snapshotter to snapshot controller and sidecar container;
- [ ]  merged attacher and provisioner to controller, as well as the rbac, crds etc.
- [ ]  enable leader election;

**Comment by malc0lm** [comment]
@Colstuwjx Ok, I will review it today, thank.

**Pull request merged**
